spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cn_test
    username: postgres
    password: J@es_2o04

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000
    refresh-expiration-ms: 604800000