spring.application.name=cn_servicies

spring.datasource.url=jdbc:postgresql://localhost:5432/cn_test
spring.datasource.username=postgres
spring.datasource.password=J@es_2o04
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

app.upload.dir=uploads
app.base-url=http://localhost:8080
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=55MB