spring.application.name=cn_servicies

spring.datasource.url=${jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

app.upload.dir=${UPLOAD_DIR:uploads}
app.base-url=${BASE_URL:http://localhost:8080}
server.port=${PORT:8080}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=55MB